default_context:
  name: "froid"
  version: "0.1.0"
  slug: "froid"
  command: "froid"
  cli: "argparse"
  config: "y"
  compat: "bpyutils"
  jupyter: "n"
  sqlite: "y"
  pypy: "y"
  description: "A ROS package for First Responder Drone"
  author: "Achilles Rasquinha"
  email: "achillesrasquinha@gmail.com"
  keywords: "ros package first responder drone"
  license: "MIT License"
  repo_service: "https://github.com"
  repo_service_username: "achillesrasquinha"
  repo_service_reponame: "froid"
  docker_service_username: "achillesrasquinha"
  docker_service_reponame: "froid"
  github_action: "n"
  ml: "y"
  editor: "vscode"
  url: "https://github.com/achillesrasquinha/froid"