#!/usr/bin/env python

from bpyutils.log import get_logger

import ezros

from froid.__attr__ import __name__ as NAME
from froid.model.tello import Tello

logger = get_logger(NAME)
        
node   = ezros.Node("tello")
tello  = Tello(docker = True)
tello.connect(wait_for_state = False, stream_on = True)

@node.on("/takeoff", mtype = None)
def handle_takeoff(msg):
    tello.takeoff()

@node.on("/land", mtype = None)
def handle_land(msg):
    tello.land()

@node.pub("/state", mtype = "froid.msg.TelloState")
def handle_state(msg):
    for attr in Tello._STATE_PROPS:
        setattr(msg, attr, getattr(tello, attr))
    return msg

@node.pub("/frame", mtype = "froid.msg.TelloFrame")
def handle_frame(msg):
    frame = tello.frame

    msg.data = frame.tobytes()

    return msg

if __name__ == "__main__":
    node.run()